version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres-tareas
    environment:
      POSTGRES_USER: tareas_user
      POSTGRES_PASSWORD: tareas_password
      POSTGRES_DB: tareasdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d   # <--- Monta tus scripts de inicialización

volumes:
  pgdata:
