name: Check secret access

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is set
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
            echo "Secret NOT found"
            exit 1
          else
            echo "Secret FOUND"
          fi
