name: Check Subscription ID secret

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Subscription ID secret is set
        run: |
          if [ -z "${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0569585AE403451FB013F4AB2A803BF7 }}" ]; then
            echo "SUBSCRIPTION ID SECRET NOT FOUND"
            exit 1
          else
            echo "SUBSCRIPTION ID SECRET FOUND"
          fi
