name: Check Azure secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Client ID secret is set
        run: |
          if [ -z "${{ secrets.AZUREAPPSERVICE_CLIENTID_789926E84599452899599970172DD70D }}" ]; then
            echo "CLIENT ID SECRET NOT FOUND"
            exit 1
          else
            echo "CLIENT ID SECRET FOUND"
          fi
